spring:
  profiles:
    active: ${PROFILE}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  jwt:
    key: ${JWT_KEY}

  h2:
    console:
      enabled: true

  management:
    endpoint:
      health:
        probes:
          enabled: true
    health:
      livenessState:
        enabled: true
      readinessState:
        enabled: true

  cloud:
    oci:
      compartment:
        static: ${OCI_COMPARTMENT}
      config:
        type: ${OCI_FILE}
      region:
        static: ${OCI_REGION}
      bucketname:
        static: ${OCI_BUCKETNAME}
      namespace:
        static: ${OCI_NAMESPACE}
      url:
        static: ${OCI_URL}
      base-profile-image-url: ${BASIC_PROFILE_IMAGE_URL}
      not-open-image-url: ${NOT_OPEN_IMAGE_URL}
      base-url: ${OCI_BASEURL:local/}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

fcm:
  url: ${FCM_URL}
  path: ${FCM_PATH:firebase/firebase-adminsdk.json}
  credential: ${FCM_CREDENTIAL}
  projectId: ${FCM_PROJECT_ID}

oauth2:
  client:
    kakao:
      client-id: ${KAKAO_CLIENT_ID}
      client-secret: ${KAKAO_CLIENT_SECRET}
      member-redirect-uri: ${KAKAO_MEMBER_REDIRECT_URI}
      creator-redirect-uri: ${KAKAO_CREATOR_REDIRECT_URI}
      admin-redirect-uri: ${KAKAO_ADMIN_REDIRECT_URI}

    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      member-redirect-uri: ${GOOGLE_MEMBER_REDIRECT_URI}
      creator-redirect-uri: ${GOOGLE_CREATOR_REDIRECT_URI}
      admin-redirect-uri: ${GOOGLE_ADMIN_REDIRECT_URI}

springdoc:
  swagger-ui:
    url: /docs/openapi3.json
    path: /api-docs/index.html

payment:
  toss:
    confirm-url: ${TOSS_CONFIRM_URL}

    secret-key: ${TOSS_TEST_SECRET_KEY}
