spring:
  application:
    name: timeToast

  config:
    activate:
      on-profile: dev

  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.2.11:3306/dev_timetoast?serverTimezone=UTC&characterEncoding=UTF-8
    username: developer
    password: TimeToast2@
    autoReconnect: True


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  management:
    endpoint:
      health:
        probes:
          enabled: true
    health:
      livenessState:
        enabled: true
      readinessState:
        enabled: true


  jwt:
    key: b06a03df1e61f3347288ad580a55904f3e7c2367179d5727e779b3ef63207bc8
