oauth2 :
  client :
    kakao :
      client-id : 00ce444e267ef1ea9be3e011dd832941
      client-secret: JJoUV7upQAS8h0t3IyDeJalj3Kim5ON2
      redirect-uri: http://localhost:8080/api/v1/login/kakao

    google :
      client-id : 456598169342-am0dppiqr6an8ea9unrcrqum7p3dner8.apps.googleusercontent.com
      client-secret: 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
      redirect-uri: http://localhost:8080/api/v1/login/google