spring:
  profiles:
    active: ${PROFILE}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  jwt:
    key: ${JWT_KEY}

  h2:
    console:
      enabled: true

  management:
    endpoint:
      health:
        probes:
          enabled: true
    health:
      livenessState:
        enabled: true
      readinessState:
        enabled: true

  cloud:
    oci:
      compartment:
        static: ${OCI_COMPARTMENT}
      config:
        type: ${OCI_FILE}
      region:
        static: ${OCI_REGION}
      bucketname:
        static: ${OCI_BUCKETNAME}
      namespace:
        static: ${OCI_NAMESPACE}
      url:
        static: ${OCI_URL}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

fcm:
  url: ${FCM_URL}
  path: ${FCM_CONFIG_PATH}
  credential: ${FCM_CREDENTIAL}

oauth2:
  client:
    kakao:
      client-id: ${KAKAO_CLIENT_ID}
      client-secret: ${KAKAO_CLIENT_SECRET}
      redirect-uri: ${KAKAO_REDIRECT_URI}

    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      redirect-uri: ${GOOGLE_REDIRECT_URI}

springdoc:
  swagger-ui:
    url: /docs/openapi3.json
    path: /api-docs/index.html
